books = [
    {
        "id": 1,
        "title": "Python Programming: An Introduction to Computer Science",
        "author": "John Zelle",
        "price": 34.99,
        "pages": 552,
        "description": "An introductory text for computer science and Python.",
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "price": 29.99,
        "pages": 464,
        "description": "A handbook of agile software craftsmanship.",
    },
    {
        "id": 3,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt and David Thomas",
        "price": 32.5,
        "pages": 352,
        "description": "Classic advice for software developers.",
    },
    {
        "id": 4,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "price": 28.0,
        "pages": 592,
        "description": "Practical Python for everyday automation.",
    },
    {
        "id": 5,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "price": 45.0,
        "pages": 770,
        "description": "Deep dive into modern Python idioms.",
    },
    {
        "id": 6,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "price": 39.95,
        "pages": 544,
        "description": "A hands-on introduction to Python programming.",
    },
    {
        "id": 7,
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen",
        "price": 89.99,
        "pages": 1312,
        "description": "A standard reference for algorithms.",
    },
    {
        "id": 8,
        "title": "Design Patterns",
        "author": "Erich Gamma",
        "price": 47.5,
        "pages": 395,
        "description": "Elements of reusable object-oriented software.",
    },
    {
        "id": 9,
        "title": "Grokking Algorithms",
        "author": "Aditya Bhargava",
        "price": 24.99,
        "pages": 256,
        "description": "An illustrated guide to algorithms.",
    },
    {
        "id": 10,
        "title": "Deep Learning with Python",
        "author": "Francois Chollet",
        "price": 49.99,
        "pages": 384,
        "description": "Introduces deep learning with Keras and Python.",
    },
]